- name: mailserver setup
- hosts: mailservers
  become: true  
  vars:
    mail_domain: "example.com" # Definieren Sie hier Ihre fiktive Domain

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Postfix
      apt:
        name: postfix
        state: present
      notify:
        - restart postfix
      when: ansible_hostname == "mailserver1" or ansible_hostname == "mailserver2"

    - name: Configure Postfix (responsefile) - Internet Site
      debconf:
        name: postfix
        question: mail_server_type
        value: 'Internet Site'
        vtype: select
      when: ansible_hostname == "mailserver1" or ansible_hostname == "mailserver2"

    - name: Configure Postfix (responsefile) - System mail name
      debconf:
        name: postfix
        question: mail_name
        value: "{{ ansible_hostname }}.{{ mail_domain }}"
        vtype: string
      when: ansible_hostname == "mailserver1" or ansible_hostname == "mailserver2"

    - name: Install Dovecot
      apt:
        name:
          - dovecot-core
          - dovecot-imapd
          - dovecot-pop3d
        state: present
      notify:
        - restart dovecot
      when: ansible_hostname == "mailserver1" or ansible_hostname == "mailserver2"

  handlers:
    - name: restart postfix
      service:
        name: postfix
        state: restarted

    - name: restart dovecot
      service:
        name: dovecot
        state: restarted
