---
- hosts: mailservers
  become: true  
  vars:
    mail_domain: ".com"

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Postfix
      apt:
        name: postfix
        state: present
      notify:
        - restart postfix

    - name: Configure Postfix Internet Site
      debconf:
        name: postfix
        question: mail_server_type
        value: 'Internet Site'
        vtype: select

    - name: Configure Postfix System mail name
      debconf:
        name: postfix
        question: mail_name
        value: "{{ ansible_hostname }}.{{ mail_domain }}"
        vtype: string

    - name: Install Dovecot
      apt:
        name:
          - dovecot-core
          - dovecot-imapd
          - dovecot-pop3d
        state: present
      notify:
        - restart dovecot

  handlers:
    - name: restart postfix
      service:
        name: postfix
        state: restarted

    - name: restart dovecot
      service:
        name: dovecot
        state: restarted
